### ISSUE TITLE
TeamCity exceptions and Stash build status not updated during Pull request

### ISSUE THREAD

**Issue by nishaatr** [mendhak/teamcity-stash#30]
We have been seeing frequent exceptions in TeamCity:

[2016-06-13 13:49:03,915]  ERROR -   jetbrains.buildServer.SERVER - TEAMCITY-STASH:Could not send data to Stash.  
java.io.IOException: Server returned HTTP response code: 401 for URL: https://stash-server/rest/build-status/1.0/commits/1223f29d516dc12598ff3ddb916ebc3105b73138
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)

Also, developers are reporting that sometimes build status in Stash is not updated during Pull request and/or when TeamCity build fails. 

Are these known issues or perhaps you can help us debug the root cause?

Thanks
Nish

**Comment by mendhak** [comment]
401 usually indicates a bad username/password.  For example, if the user is disabled, locked out, captcha, deleted, or just bad password entered.  

You can also look at Stash's atlassian-stash.log under STASH_HOME's log folder (Example: /Stash-Home/log/atlassian-stash.log) file to see what it did with the HTTP request sent by the plugin. In the log file, search for POST /rest/build-status as a starting point.

**Comment by nishaatr** [comment]
Thanks for the reply. We will check the Stash logs.


Get Outlook for Android






On Mon, Jun 20, 2016 at 8:29 PM +0100, "mendhak" <notifications@github.com> wrote:





401 usually indicates a bad username/password.  For example, if the user is disabled, locked out, captcha, deleted, or just bad password entered.

You can also look at Stash's atlassian-stash.log under STASH_HOME's log folder (Example: /Stash-Home/log/atlassian-stash.log) file to see what it did with the HTTP request sent by the plugin. In the log file, search for POST /rest/build-status as a starting point.

---

**Comment by anditburns** [comment]
We are seeing the same problem and it is defiantly not a bad username/password problem. We are seeing this probably in about 1 in 10 stash commits where the build status does not report anything.

**Comment by nishaatr** [comment]
Any further thoughts mendhak (in light of comments from anditburns)?

**Comment by mendhak** [comment]
What did the Stash logs say?

**Comment by iancrowther** [comment]
I ran into this issue and was able to work around it by creating a new user.  I would expect to get a similar result if you "recreate" the existing user.

As for why its broken.. I have no answer.

Hope that helps!
