### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by FrankPeach** [mendhak/teamcity-stash#31]
Installed plugin to Teamcity 9.1.3 am getting this error

[2017-01-17 10:59:10,237]  ERROR -   jetbrains.buildServer.SERVER - TEAMCITY-STASH:Could not send data to Stash.  
java.io.FileNotFoundException: https://bitbucket.org/signzoneinc/rest/build-status/1.0/commits/8ea3a409ef151d9677dd8003f612a515ba3731e9
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at mendhak.teamcity.stash.api.StashClient.PostBuildStatusToStash(StashClient.java:149)
	at mendhak.teamcity.stash.api.StashClient.SendBuildStatus(StashClient.java:118)
	at mendhak.teamcity.stash.ChangeStatusUpdater$1$1.run(ChangeStatusUpdater.java:184)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mendhak** [comment]
This plugin won't work with the public bitbucket code repo.  I had a look at the JetBrains plugin and theirs doesn't do it either.  

https://confluence.jetbrains.com/display/TW/Commit+Status+Publisher

This plugin is only for Bitbucket Server (hosted on-premise)
